rabbit@Ahasver:~/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1$ prove -I/home/rabbit/devel/dbic/lib -l t/20-dbic.t 
t/20-dbic.t .. 1/? 


I got called with DBIx::Error::UniqueViolation=HASH(0x39e4b80)
   at /home/rabbit/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1/lib/DBIx/Error.pm line 309.
	DBIx::Error::__ANON__() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1094
	eval {...} called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1115
	DBIx::Class::Schema::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 113
	DBIx::Class::Storage::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 183
	DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Context/Preserve.pm line 27
	Context::Preserve::preserve_context() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 212
	DBIx::Class::Storage::BlockRunner::_run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 105
	DBIx::Class::Storage::BlockRunner::run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 187
	DBIx::Class::Storage::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 871
	DBIx::Class::Storage::DBI::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 657
	DBIx::Class::Schema::txn_do() called at t/20-dbic.t line 38
	Test::Exception::throws_ok() called at t/20-dbic.t line 39



I got called with DBIx::Error::NotNullViolation=HASH(0x39a4418)
   at /home/rabbit/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1/lib/DBIx/Error.pm line 309.
	DBIx::Error::__ANON__() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1094
	eval {...} called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1115
	DBIx::Class::Schema::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 113
	DBIx::Class::Storage::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 183
	DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Context/Preserve.pm line 27
	Context::Preserve::preserve_context() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 212
	DBIx::Class::Storage::BlockRunner::_run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 105
	DBIx::Class::Storage::BlockRunner::run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 187
	DBIx::Class::Storage::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 871
	DBIx::Class::Storage::DBI::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 657
	DBIx::Class::Schema::txn_do() called at t/20-dbic.t line 47
	Test::Exception::throws_ok() called at t/20-dbic.t line 48



I got called with DBIx::Class::Exception=HASH(0x3a6e150)
   at /home/rabbit/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1/lib/DBIx/Error.pm line 309.
	DBIx::Error::__ANON__() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1094
	eval {...} called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1115
	DBIx::Class::Schema::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 113
	DBIx::Class::Storage::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 183
	DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Context/Preserve.pm line 27
	Context::Preserve::preserve_context() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 212
	DBIx::Class::Storage::BlockRunner::_run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 105
	DBIx::Class::Storage::BlockRunner::run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 187
	DBIx::Class::Storage::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 871
	DBIx::Class::Storage::DBI::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 657
	DBIx::Class::Schema::txn_do() called at t/20-dbic.t line 60
	Test::Exception::throws_ok() called at t/20-dbic.t line 61

#   Failed test 'threw DBIx::Error'
#   at t/20-dbic.t line 61.
# expecting: DBIx::Error
# found: DBIx::Class::Exception (DBIx::Class::Storage::DBI::_dbh_execute_for_fetch(): execute_for_fetch() aborted with 'PRIMARY KEY must be unique' at populate slice:
# {
#   id => 1,
#   name => "You"
# } at t/20-dbic.t line 57
# )



I got called with TestError=HASH(0x3a10560)
   at /home/rabbit/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1/lib/DBIx/Error.pm line 309.
	DBIx::Error::__ANON__() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1094
	eval {...} called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1115
	DBIx::Class::Schema::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 113
	DBIx::Class::Storage::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 183
	DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Context/Preserve.pm line 27
	Context::Preserve::preserve_context() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 212
	DBIx::Class::Storage::BlockRunner::_run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 105
	DBIx::Class::Storage::BlockRunner::run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 187
	DBIx::Class::Storage::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 871
	DBIx::Class::Storage::DBI::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 657
	DBIx::Class::Schema::txn_do() called at t/20-dbic.t line 69
	Test::Exception::throws_ok() called at t/20-dbic.t line 70
# Looks like you failed 1 test of 6.
t/20-dbic.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests 

Test Summary Report
-------------------
t/20-dbic.t (Wstat: 256 Tests: 6 Failed: 1)
  Failed test:  5
  Non-zero exit status: 1
Files=1, Tests=6,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.57 cusr  0.02 csys =  0.62 CPU)
Result: FAIL
